config/routes.rb
Rails.application.routes.draw do

devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => {:registrations => "user_registrations"}
resources :users
  resources :products do
    resources :comments
end



resources :orders, only: [:index, :show, :create, :destroy]


root 'static_pages#landing_page'

get '/static_pages/about'

get 'static_pages/contact'

get 'static_pages/landing_page'

get 'static_pages/index'

get 'static_pages/thank_you'

post 'static_pages/thank_you'




end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
 scope :rating_desc, -> { order(rating: :desc) }
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :product
  belongs_to :user

end

app/models/product.rb
class Product < ApplicationRecord
has_many :orders
has_many :comments


def highest_rating_comment
		comments.rating_desc.first
	end
	
	def average_rating
		comments.average(:rating).to_f
end


def self.search(search_term)
		like_string = Rails.env.production? ? "ilike" : "LIKE"
		Product.where("name #{like_string} ?", "%#{search_term}%")
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 has_many :orders
has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end




  # adding field first_name  last_name to devise
 # before_action :configure_permitted_parameters, if: :devise_controller?

   # protected

   # def configure_permitted_parameters
     # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
   # end










  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_user, only: [:destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

	def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user
    respond_to do |format|
      if @comment.save
        #ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :body, :rating)
    end

      # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders=Order.all
    @products = Product.all
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :set_product, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
 
 
  # GET /products/1
  # GET /products/1.json
  def show
  @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
end
def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
end

private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end



  private
    # Use callbacks to share common setup or constraints between actions.
   def set_product
      @product = Product.find(params[:id])
end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

 def landing_page
  	#if Product.first
  		@featured_product = Product.first
  		@products = Product.limit(3)
   # else
     # @products = nil
  	#end
  end


  def index
  end

   def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  ActionMailer::Base.mail(from: @email,
      to: 'mahdi.nirmeen@gmail.com',
      subject: "A new contact form message from #{@name}",
      body: @message).deliver_now
end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
	  before_action :configure_permitted_parameters, :only => [:create]

  def create
    super
    if @user.persisted?
     #ٍٍٍٍٍ UserMailer.welcome(@user).deliver_now
    end
  end

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end



  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <src="https://code.jquery.com/jquery-3.2.1.min.js"integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="crossorigin="anonymous">
</script>
    
 

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

     <%= csrf_meta_tag %>
</head>
<body>




  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <!-- Sign up Log in -->

        <div class="navbar-form navbar-left">
         <ul class="nav navbar-nav navbar-left">
              <li>
                  </li>
                <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete, class:"btn btn-default fa fa-sign-in") %>  </li> 
 <li>
  <%= link_to('Edit User', edit_user_registration_path, :method => :get, class:"btn btn-default fa fa-pencil-square-o" ) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path, :method => :get, class:"btn btn-default fa fa-sign-in")  %></li> <li>
 <%= link_to('Register', new_user_registration_path, :method => :get, class:"btn btn-default fa fa-user" ) %>   

  </li>
<% end %>
            </ul>
        </div>



        <!-- Search Box -->
       <%= form_tag(products_path, method: "get", class: "navbar-form navbar-right") do %>
                    <%= text_field_tag(:q, "", type: "text", class: "form-control", placeholder: "search text") %>
                    <%= submit_tag("Search", class: "btn btn-primary") %>

                <% end %>


        <ul class="nav navbar-nav navbar-center">
          <li>
                  <a href="../">Home</a>
                </li>
           <li><a href="../products/">Products</a></li>            
                 <li><%= link_to 'About', static_pages_about_path %></li>
                <li><%= link_to 'Contact', static_pages_contact_path %></li></ul>
       
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>  
  
  <section class="container-fluid minpage">

    <!-- Flash Notice Tags -->
    <% if notice %>
      <div id="notice" class="alert alert-warning"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>
  </section>

  
 <!--Footer Section -->
  <div class="footer-container">
      <h4 class="_14">Follow me on</h4>
    <div class="social-icons">
        <li><a href="https://www.facebook.com/NerminMahdi20" class="social-icon"> <i class="fa fa-facebook"></i></a></li>
        <li><a href="https://twitter.com/nerminmahdi" class="social-icon"> <i class="fa fa-twitter"></i></a></li>
    </div>
    <p> &copy; Web Development by Nermin M. Mahdi 2017</p>
</div>

  <!--End Footer Section -->

</body>

</html>

app/views/orders/index.html.erb
<h1>Orders</h1>

app/views/orders/show.html.erb
<p> show order page</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

<div class="field">
  <%= form.label :colour %><br>
  <%= form.text_field :colour%>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

 <div><%= link_to 'New Product', new_product_path %></div>
 <ul class="first">
   



<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
    <div class="columns">
      <ul class="product">
 <li class="header"><%= product.name %></li>
 <li><%= product.description %></li>
 <li class="data"><%= image_tag(product.image_url, class: "img-responsive") %></li>
 <li class="header"><%= product.color%></li>
 <li class="action"><%= link_to 'Show', product %> 
 <%= link_to 'Edit', edit_product_path(product) %>
 <%= link_to 'Destroy', product, method: :delete, data:{ confirm: 'Are you sure?' } %></a></li>
      </ul>
</div>
    <% end %>
  </div>
</div>
  
<br>

app/views/products/new.html.erb
<link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine">

    <style>
      body {
        font-family: 'Tangerine', serif;
        font-size: 38px;
        color:red;
        text-align:center;
      }
    </style>
<div class= container> 
    <div>  Create New Product</div><br>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>colour:</strong>
  <%= @product.color %>
</p>
 <p>Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>
 <div class="row" id="comments-section">
    <div class="col-xs-12 col-sm-9">
      <%= render  'new_comment' %>
      <div class="alert alert-info" style="display:none" role="alert">A new comment has been posted!</div>
      <%= render 'comments' %>
</div>
<%= link_to 'Edit', edit_product_path(@product) %> 
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<div class="container-fluid anchor bg-workandabout" id="workpage">
  <div class="resize intro">
<html>
  <head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=decaying">
    <style>
      body {

        text-align:center;
      }
    </style>
  </head>
  <body>
    <div  class="glyphicon glyphicon-heart">ABOUT-US</div>
<article class="container">
  <div class="row"> 
    <div class = "col-md-6 col-sm-6 col-xs-12 about">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span><h2>EXPERIENCED STAFF</h2>
       <p>The experience of parents is transmitted by children</p>
    </div>
    <div class = "col-md-6 col-sm-6 col-xs-12 about">
      <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><h2>EXPERT SELLING</h2>
        <p>Staff trained and experienced to deal with all types of customers</p>
    </div>
  </div>
  <div class="row">  
    <div class = "col-md-6 col-sm-6 col-xs-12 about">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span><h2>WORK TIME</h2>
        <p>Business services are available 24 hours a day</p>
    </div>
    <div class = "col-md-6 col-sm-6 col-xs-12 about">
      <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span><h2>OUR DIFFERANCE</h2>
       <p>Support your local demand! Our Hand Crafted flowers are designed by local Artisan Florists and delivered same day in as little as 2 hours.</p>
    </div>
  </div> 
 
</article>




  </body>
</html>
</div><!-- end workpage -->

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1><br>

<%= flash[:notice] %>

<%= form_with(url: "/static_pages/thank_you") do |form| %>
    <%= form_tag("/static_pages/thank_you") do %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag :name %>
        <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
      </div>      
      <div class="form-group">
        <%= label_tag :email, "Email Address" %>
        <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
      </div>
      <div class="form-group">
        <%= label_tag :message %>
        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
      </div>      
    </div>
  </div>
 
  <% end %>
</div>
  <%= form.submit "Send" %>   
<% end %>

app/views/static_pages/index.html.erb
<div class="row">
  <h1>Welcome to Nermin Market</h1>
</div>
<div class="row">
  <%= image_tag("re.jpg", class: "img-responsive center-block img-prod col-md-4") %>
  <%= image_tag("re.jpg", class: "img-responsive center-block img-prod col-md-4") %>
  <%= image_tag("re.jpg", class: "img-responsive img-prod center-block col-md-4") %>
</div>
<div class="row">
  <h3>Your source of global flowers in the world</h3>
</div>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @products.each_with_index do |product, index| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= " active" if product == @products.first %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
      <div class="item<%= " active" if product == @products.first %>">
        <%= link_to image_tag(product.image_url), product %>
        <div class="carousel-caption">
          <%= product.name %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /carousel -->

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>